[project]
name = "news-article-summarisation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "datasets>=5.0.0",
    "evaluate>=0.4.6",
    "nltk>=3.9.4",
    "pandas>=3.0.3",
    "pytextrank>=3.3.0",
    "rouge-score>=0.1.2",
    "spacy>=3.8.14",
    "torch>=2.12.0",
    "transformers>=5.10.2",
]
